CREATE DATABASE IF NOT EXISTS `waimai`;

USE `waimai`;

CREATE TABLE IF NOT EXISTS `user`(
 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户登录表';

CREATE TABLE IF NOT EXISTS `user_address`(
  
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户配送地址';

CREATE TABLE IF NOT EXISTS `shop`(
  
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000 COMMENT '商家登录';


CREATE TABLE IF NOT EXISTS `shop_info`(
 

CREATE TABLE IF NOT EXISTS `shop_license`(
  
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '商家入驻许可证';

CREATE TABLE IF NOT EXISTS `food`(
 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '商品信息表';

CREATE TABLE IF NOT EXISTS `food_category`(
  
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '商家的食物分类';


CREATE TABLE IF NOT EXISTS `shop_activity` (

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '商家活动';


CREATE TABLE IF NOT EXISTS `order`(

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单主表';


CREATE TABLE IF NOT EXISTS `order_food`(

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单商品详情表';


CREATE TABLE IF NOT EXISTS `order_refund`(

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单--退款处理';


CREATE TABLE IF NOT EXISTS `order_comment`(
  
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单--评论';

CREATE TABLE IF NOT EXISTS `order_process`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR (50) COMMENT '订单ID',
  `content` VARCHAR (500) COMMENT '进度备注内容',
  `reason` VARCHAR (500) COMMENT '理由',
  `order_status` TINYINT DEFAULT 0 COMMENT '进度状态',
  `status` TINYINT DEFAULT 10 COMMENT '状态',
  `add_time` INT (11) DEFAULT 0 COMMENT '加入时间'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单--进度详情';

CREATE TABLE IF NOT EXISTS `pay`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR (50) COMMENT '订单ID',
  `user_id` INT (11) DEFAULT 0 COMMENT '用户ID',
  `shop_id` INT (11) DEFAULT 0 COMMENT '商店ID',
  `total_money` DECIMAL DEFAULT 0 COMMENT '支付总数',
  `status` TINYINT DEFAULT 10 COMMENT '状态',
  `add_time` INT(11) DEFAULT 0 COMMENT '加入时间',
  `deal_time` INT (11) DEFAULT 0 COMMENT '处理时间'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单支付表';


CREATE TABLE IF NOT EXISTS `coupon`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `coupon_id` VARCHAR (50) UNIQUE COMMENT '红包ID',
  `shop_id` INT (11) DEFAULT 0 COMMENT '商铺Id',
  `type` TINYINT DEFAULT 0 COMMENT '红包类型',
  `title` VARCHAR (20) COMMENT '红包标题',
  `target_money` DECIMAL DEFAULT 0 COMMENT '需要满足的金额',
  `discount_money` DECIMAL DEFAULT 0 COMMENT '优惠金额',
  `end_time` INT (11) DEFAULT 0 COMMENT '结束时间',
  `add_time` INT (11) DEFAULT 0 COMMENT '加入时间',
  `number` VARCHAR (20) DEFAULT 0 COMMENT '可以领取的数量',
  `status` TINYINT DEFAULT 10 COMMENT '状态'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '(红包)满减优惠发布表';



CREATE TABLE IF NOT EXISTS `deliver`(

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '送餐员信息表';


CREATE TABLE IF NOT EXISTS `deliver_task`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR (50) COMMENT '订单ID',
  `deliver_id` INT (11) DEFAULT 0 COMMENT '送餐员ID',
  `send_cost` DECIMAL DEFAULT 0 COMMENT '配送费',
  `add_time` INT (11) DEFAULT 0 COMMENT '加入时间',
  `status` TINYINT DEFAULT 10 COMMENT '状态'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单配送表';



CREATE TABLE IF NOT EXISTS `admin_user`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `account` VARCHAR (50) NOT NULL UNIQUE COMMENT '登录账号',
  `password` VARCHAR (50) NOT NULL COMMENT '登录密码',
  `username` VARCHAR (20) COMMENT '用户名字',
  `group_id` INT (11) DEFAULT 0 COMMENT '管理组ID',
  `last_login` VARCHAR (500) COMMENT '上次登录信息',
  `status` TINYINT DEFAULT 10 COMMENT '状态',
  `add_time` INT (11) DEFAULT 0 COMMENT '加入时间'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '管理员信息表';


CREATE TABLE IF NOT EXISTS `admin_log`(
  `id` INT (11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键',
  `server_id` INT DEFAULT 0 COMMENT '服务器ID',
  `admin_id` INT (11) DEFAULT 0 COMMENT '管理员ID',
  `username` VARCHAR (50) COMMENT '管理者名字',
  `controller` VARCHAR (50) COMMENT '控制器',
  `action` VARCHAR (50) COMMENT '动作',
  `detail` VARCHAR (500) COMMENT '详情',
  `ip` VARCHAR (50) COMMENT 'IP',
  `result` VARCHAR (500) COMMENT '操作结果',
  `status` TINYINT DEFAULT 10 COMMENT '状态',
  `add_time` INT (11) DEFAULT 0 COMMENT '加入时间'

)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '管理员操作日志';